### ISSUE TITLE
Amazing game

### ISSUE THREAD

**Issue by BogusCurry** [andrewpey/open-voxel-tycoon#7]
Hello ;D
I found this game over Twitter, have follow mashinky ;D Now I so amazing from the VoxelTycon game. I hope the release comes jan 2018 ;D I would donate make for you game. 

On question from me, in which language comes the game on steam ? I comes from germany and so I hope the game comes in my mouther language. But in englisch was no problem for me ;D

Have a nice Day ;D

Bogus

**Comment by andrewpey** [comment]
Hey Bogus! Thank you for the kind words.

We will use the help of the community for game localization, so more and more languages will be added eventually. Can't say which of them will be in the game on release.

Now I'm closing this issue as this repo is intended to discuss and suggest features of the game but it isn't the best place to ask common questions. You can always ask anything you want on our [Discord Server](http://discord.gg/64KPWd5) or [social networks](http://voxeltycoon.xyz/contacts).
